export const demoUsers = [
  { id: "demo-ashish", name: "Ashish", email: "ashish@example.com", role: "OWNER" },
  { id: "demo-terri", name: "Terri", email: "terri@example.com", role: "MEMBER" },
];

export const demoLeads = [
  {
    id: "demo-1",
    businessName: "Maple Street Dental",
    category: "Dentist",
    phone: "(919) 555-0134",
    email: "hello@maplestreetdental.test",
    website: "https://example.com",
    address: "214 Maple St",
    city: "Raleigh",
    state: "NC",
    googlePlaceId: "demo-place-1",
    googleMapsUrl: "https://maps.google.com",
    googleRating: 4.7,
    googleReviewCount: 38,
    status: "FOLLOW_UP",
    websiteScore: 62,
    pageSpeedPerformance: 58,
    pageSpeedAccessibility: 83,
    pageSpeedSEO: 71,
    pageSpeedBestPractices: 76,
    notes: "Owner asked for examples of booking flow improvements.",
    assignedToId: "demo-ashish",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-2",
    businessName: "Bright Oak Roofing",
    category: "Roofing Contractor",
    phone: "(919) 555-0188",
    email: null,
    website: null,
    address: "88 Oak Ridge Rd",
    city: "Durham",
    state: "NC",
    googlePlaceId: "demo-place-2",
    googleMapsUrl: "https://maps.google.com",
    googleRating: 4.9,
    googleReviewCount: 19,
    status: "NEW",
    websiteScore: null,
    pageSpeedPerformance: null,
    pageSpeedAccessibility: null,
    pageSpeedSEO: null,
    pageSpeedBestPractices: null,
    notes: "No public website listed.",
    assignedToId: "demo-terri",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-3",
    businessName: "Pine & Co. Salon",
    category: "Hair Salon",
    phone: "(984) 555-0105",
    email: "frontdesk@pineco.test",
    website: "https://example.org",
    address: "450 Franklin Ave",
    city: "Chapel Hill",
    state: "NC",
    googlePlaceId: "demo-place-3",
    googleMapsUrl: "https://maps.google.com",
    googleRating: 4.5,
    googleReviewCount: 73,
    status: "MEETING_BOOKED",
    websiteScore: 74,
    pageSpeedPerformance: 68,
    pageSpeedAccessibility: 91,
    pageSpeedSEO: 80,
    pageSpeedBestPractices: 88,
    notes: "Booked discovery call for Thursday.",
    assignedToId: "demo-ashish",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoNotes = [
  {
    id: "demo-note-1",
    leadId: "demo-1",
    userId: "demo-ashish",
    note: "Left voicemail with a concise website audit hook.",
    callOutcome: "LEFT_VOICEMAIL",
    followUpDate: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date().toISOString(),
    user: demoUsers[0],
  },
];
